version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
  test:
    build:
      context: ./client
      dockerfile: Dockerfile.test
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - client
    command: npx playwright test
